### PR TITLE
do not put hyphens into code arbitrarily, it is confusing to readers

### PR DESCRIPTION
**Pull request by wbbradley**

### CODE REVIEW

**Comment by brenankeller** [comment]
@wbbradley I was never a fan of this either. After attempting to remove this previously, I think there were display issues in the code snippets, especially with long urls. Have you built this locally and confirmed code snippets are still readable/fully visible?

**Comment by wbbradley** [comment]
@brenankeller I'll check that now. I suppose we should have some level of support for window width... Like, we only support down to a certain width.

**Comment by wbbradley** [comment]
The behavior with this change is that the word breaks can occur mid word. I still prefer this to adding a hyphen. The hyphen is not an uncommon character in apis, so it would not be surprising to me if someone was confused by the hyphen. The line break is fairly simple to understand... not sure which is more important. I may just leave this alone for now.

**Comment by brenankeller** [comment]
I agree it's confusing. Is there an easy way for us to keep the line breaks but not add a dash?

**Comment by brenankeller** [comment]
We'll need that or some form of horizontal scrolling since some of these URLs are quite long.

**Pull request closed without merging**
